### ISSUE TITLE
client side localize querybuilder 

### ISSUE THREAD

**Issue by Cuiqs76** [syncfusion/blazor-locale#1]
syncfusionwould you privde a client side  localization sample? i follow the documemt to localize querybuilder control, but failed. i download the new json from github.  sf version 18.1.0.44.

**Comment by arunkumar205** [comment]
Hi Team, 
 
We have checked your reported issue about localization for clientside and we would inform you that your mentioned localization doucumentation is only for server side. So that you are facing this kind of issue. We suggest you to refer the below documentation link for client side localization.  
 
Documentation for client side localization: 
https://blazor.syncfusion.com/documentation/common/localization/#web-assembly-application 
 
We have created the sample for this scenario. Please refer the below sample link. 
 
Sample Link: 
https://www.syncfusion.com/downloads/support/directtrac/273402/ze/BlazorApp29-1408527661 
 
Please get back to us if you need further assistance. 
 
Regards, 
Arunkumar D
