### ISSUE TITLE
FR : pâte -> coller (to paste)

### ISSUE THREAD

**Issue by DjeeBay** [syncfusion/blazor-locale#134]
Hi,

This [PR](https://github.com/syncfusion/blazor-locale/pull/129/commits) has been merged but in 24.x the translation is wrong again.
In French, "to paste" = "Coller"
In your resx, "to paste" is "Pâte" which means pasta in english.

Please replace "Pâte" by "Coller" wherever it occurs.

Edit : applies also on fr-CH.resx

**Comment by kmuthukumarmkm** [comment]
Hi @DjeeBay 

Due to our internal circumference, the merged changes were reverted. Sorry for the inconvenience caused.

However, now we have corrected it and merged. Same changes we included in our internal level also.

PRs: [137](https://github.com/syncfusion/blazor-locale/pull/137), [138](https://github.com/syncfusion/blazor-locale/pull/138)

Thanks,
Muthukumar K
